import type { Metadata } from "next";
import { Geist, Geist_Mono, Cutive } from "next/font/google";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

const cutive = Cutive({
  weight: "400",
  variable: "--font-cutive",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="en"
      className={`${geistSans.variable} ${geistMono.variable} ${cutive.variable} h-full antialiased`}
    >
      <body className="font-sans min-h-full flex flex-col bg-slate-50 text-slate-900">{children}</body>
    </html>
  );
}
