import type { Metadata } from "next";
import { Geist, Geist_Mono, Inter } from "next/font/google";
import { CollaboratorsProvider } from "@/components/CollaboratorsContext";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

const inter = Inter({
  variable: "--font-inter",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
      <html
        lang="en"
        className={`${geistSans.variable} ${geistMono.variable} ${inter.variable} h-full antialiased`}
      >
        <body className="font-sans min-h-full flex flex-col bg-slate-50 text-slate-900 leading-relaxed">
          <CollaboratorsProvider>
            {children}
          </CollaboratorsProvider>
        </body>
    </html>
  );
}
